### ISSUE TITLE
Broadcast not supported

### ISSUE THREAD

**Issue by williamleong** [bitcraze/crazyradio2-firmware#1]
Using release 1.0 with Crazyswarm2 but it prompts that broadcast is not supported:

````
[crazyflie_server-3] terminate called after throwing an instance of 'std::runtime_error'
[crazyflie_server-3]   what():  Issue with connection radiobroadcast://*/80/2M. Your radio with firmware 3.2 does not support broadcast communication. Please upgrade your Crazyradio firmware!
````

**Comment by ataffanel** [comment]
This is a bug in Crazyswarm2: Crazyradio 2.0 does support broadcast packets. Crazyswarm2 needs to be updated.

**Comment by knmcguire** [comment]
Actually, Crazyradio 2.0 does support broadcasting, but since the firmware version check in crazyswarm2 is hardcoded, this fails...  If you search for 'Your radio with firmware...' in the full code base, you can perhaps comment out that assert so it doesn't fail. 

Here is an issue linked to that: https://github.com/IMRCLab/crazyswarm2/issues/245. Could you post your issue over there? I think that is a better locaiton for it.

**Comment by williamleong** [comment]
Thanks @knmcguire, have updated that issue and will try what you suggested.
